# Generated by Django 4.2.5 on 2024-07-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0005_alter_predictionsession_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredictionSession',
        ),
    ]
