# Generated by Django 4.2.5 on 2024-07-08 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0007_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
