# Generated by Django 4.2.5 on 2024-07-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0008_history_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='model_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
